#!/usr/bin/env bash
# shellcheck disable=SC2155
#
# scripts/audit-pnpm-side-worktree.sh
#
# Sets up an isolated git worktree where we can run `pnpm install` + the full
# Nx matrix without touching the main Yarn-based dev environment. Used by
# PR 1 (dep hygiene) to discover phantom deps, postinstall requirements,
# syncpack behaviour under workspace:*, and to verify the final dep graph.
#
# Idempotent: running twice reuses the existing worktree and refreshes the
# generated config files.
#
# Usage: ./scripts/audit-pnpm-side-worktree.sh
#        ./scripts/audit-pnpm-side-worktree.sh --reset   # wipe & recreate
#
# After running, cd into the printed path and invoke pnpm manually:
#   cd ../castore-pnpm-audit
#   pnpm install                                  # phantom-deps pass 1
#   pnpm nx run-many --target=test-type,...       # runtime phantom-deps
#
# The side worktree's node_modules and any audit scratch files stay out of
# git via the worktree's own .gitignore (unchanged from the source branch).

set -euo pipefail

readonly REPO_ROOT="$(git rev-parse --show-toplevel)"
readonly WORKTREE_PATH="${REPO_ROOT}/../castore-pnpm-audit"
readonly PNPM_HOME_PATH="${WORKTREE_PATH}/.pnpm-home"
readonly PNPM_STORE_PATH="${WORKTREE_PATH}/.pnpm-store"

log() { printf '[audit] %s\n' "$*"; }
die() { printf '[audit] ERROR: %s\n' "$*" >&2; exit 1; }

if [[ "${1:-}" == "--reset" ]]; then
  if git -C "${REPO_ROOT}" worktree list --porcelain | grep -q "worktree ${WORKTREE_PATH}$"; then
    log "Removing existing worktree at ${WORKTREE_PATH}"
    git -C "${REPO_ROOT}" worktree remove --force "${WORKTREE_PATH}"
  fi
  rm -rf "${WORKTREE_PATH}"
fi

command -v pnpm >/dev/null 2>&1 || die "pnpm not found on PATH. Install via 'corepack enable' or 'npm i -g pnpm'."
command -v git >/dev/null 2>&1 || die "git not found on PATH."

readonly CURRENT_BRANCH="$(git -C "${REPO_ROOT}" branch --show-current)"
[[ -n "${CURRENT_BRANCH}" ]] || die "Could not resolve current branch (detached HEAD?)."

if ! git -C "${REPO_ROOT}" worktree list --porcelain | grep -q "worktree ${WORKTREE_PATH}$"; then
  log "Creating worktree at ${WORKTREE_PATH} from branch ${CURRENT_BRANCH}"
  git -C "${REPO_ROOT}" worktree add --detach "${WORKTREE_PATH}" "${CURRENT_BRANCH}"
else
  log "Worktree already exists at ${WORKTREE_PATH} — reusing"
fi

log "Copying audit .npmrc into worktree root"
cp "${REPO_ROOT}/scripts/audit/.npmrc" "${WORKTREE_PATH}/.npmrc"

log "Generating pnpm-workspace.yaml in worktree (scope mirrors root workspaces field)"
cat > "${WORKTREE_PATH}/pnpm-workspace.yaml" <<'YAML'
# Generated by scripts/audit-pnpm-side-worktree.sh — do NOT edit in-place.
# Mirrors the root package.json "workspaces" field for audit purposes only.
packages:
  - 'packages/*'
  - 'demo/*'
  - 'docs'
YAML

log "Preparing isolated pnpm paths (PNPM_HOME, store-dir)"
mkdir -p "${PNPM_HOME_PATH}" "${PNPM_STORE_PATH}"

# Append store-dir to the side-worktree .npmrc so the audit doesn't pollute
# the developer's global pnpm store.
cat >> "${WORKTREE_PATH}/.npmrc" <<NPMRC

# Isolated store — keeps audit fetches out of the developer's global pnpm store.
store-dir=${PNPM_STORE_PATH}
NPMRC

cat <<SUMMARY

=== pnpm audit side-worktree ready ===

  Path:         ${WORKTREE_PATH}
  Branch:       ${CURRENT_BRANCH} (detached)
  PNPM_HOME:    ${PNPM_HOME_PATH}
  Store dir:    ${PNPM_STORE_PATH}

  .npmrc contents:
$(sed 's/^/    /' "${WORKTREE_PATH}/.npmrc")

  pnpm-workspace.yaml contents:
$(sed 's/^/    /' "${WORKTREE_PATH}/pnpm-workspace.yaml")

Next steps (run manually):
  export PNPM_HOME="${PNPM_HOME_PATH}"
  cd ${WORKTREE_PATH}
  pnpm install                                  # capture ERR_PNPM_UNDECLARED_DEPENDENCY output
  pnpm nx run-many --target=test-type,test-unit,test-linter,test-circular,test-stylelint,package --all

To tear down:
  ${0} --reset

SUMMARY
